# Generated by Django 2.0.4 on 2018-04-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('mp4', models.FileField(upload_to='uploads/')),
                ('srt', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
