# Generated by Django 2.0.4 on 2018-04-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='scale',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
